workflows:
  react-native-ios-workflow:
    name: React Native iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      # Node sürümünü koruduk
      vars:
        GOOGLE_MAPS_API_KEY: Encrypted
      node: 20.19.5
    
    # Yeni eklenen: Önbellekleme (Caching) Ayarları
    # Bu ayarlar, tekrarlanan derlemelerde bağımlılıkların tekrar indirilmesini engeller.
    cache:
      cache_paths:
        # Android (Gradle) Bağımlılıkları için
        - ~/.gradle/caches
        # iOS (CocoaPods) Bağımlılıkları için
        - ~/Library/Caches/CocoaPods
        # Node Bağımlılıkları için
        - $CM_BUILD_DIR/node_modules

    scripts:
      
      # 1. Adım: Ruby Sürümünü Yapılandır (Kritik: securerandom hatasını çözer)
      - name: Configure Ruby & CocoaPods
        script: |
          # rbenv ile Ruby sürümünü 3.2.2'ye yükselt
          rbenv global 3.2.2 
          rbenv rehash
          
          echo "Kullanılan Ruby Versiyonu: $(ruby --version)"
          
          # CocoaPods'u yeniden yükle
          gem install cocoapods
          echo "Kullanılan CocoaPods Versiyonu: $(pod --version)"

      # 2. Adım: Bağımlılıkları Yükle (Kritik: Boost checksum ve önbellek sorunlarını çözer)
      - name: Install dependencies
        script: |
          # NPM bağımlılıklarını yükle
          npm install --legacy-peer-deps
          
          cd ios
          
          # Önceki pod bağımlılıklarını ve kilit dosyasını kaldırarak temiz kurulumu garantile
          echo "Önceki Pod dosyaları temizleniyor..."
          rm -f Podfile.lock
          rm -rf Pods
          
          # CocoaPods önbelleğini tamamen temizle (Boost checksum hatası için önemli)
          pod cache clean --all
          
          # Podları repo'yu güncelleyerek ve temiz kurulum yaparak yükle
          pod install --repo-update --clean-install

      # 3. Adım: iOS Derlemesi
      - name: iOS build
        script: |
          cd ios
          # Xcode projesini derle
          xcodebuild -workspace MapApp.xcworkspace -scheme MapApp -sdk iphoneos -configuration Release