workflows:
  react-native-ios-workflow:
    name: React Native iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        GOOGLE_MAPS_API_KEY: Encrypted
      node: 20.19.5   
    scripts:
      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
          cd ios
          sudo gem install cocoapods -v 1.16.2
          pod cache clean boost
          pod install --repo-update
      - name: iOS build
        script: |
          cd ios
          xcodebuild -workspace MapApp.xcworkspace -scheme MapApp -sdk iphoneos -configuration Release
