workflows:
  react-native-ios-workflow:
    name: React Native iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      # Daha yeni bir Xcode imajına geçmek en iyisidir.
      # Varsayılan MacOS imajı, kullanılan Ruby sürümünü etkiler.
      # Örneğin: xcode: 15.0.1 (Codemagic ayarlarında bu seçeneği bulmalısınız)
      vars:
        GOOGLE_MAPS_API_KEY: Encrypted
      node: 20.19.5
    
    scripts:
      
      - name: Install Ruby 3.2 and CocoaPods
        script: |
          # Ruby 3.2.2 sürümüne geçerek 'securerandom' hatasını çöz
          rbenv global 3.2.2 
          rbenv rehash
          
          echo "Kullanılan Ruby Versiyonu: $(ruby --version)"
          
          # CocoaPods'u tekrar yükle
          gem install cocoapods

      - name: Install dependencies
        script: |
          npm install --legacy-peer-deps
          
          cd ios
          
          # Önceden kalan pod bağımlılıklarını ve kilit dosyasını kaldır
          echo "Önceki Pod dosyaları temizleniyor..."
          rm -f Podfile.lock
          rm -rf Pods
          
          # CocoaPods önbelleğini tamamen temizle (Boost checksum hatasını çözmeye yardımcı olabilir)
          pod cache clean --all
          
          # Podları temiz bir şekilde yükle ve reposu güncelle
          pod install --repo-update --clean-install

      - name: iOS build
        script: |
          cd ios
          xcodebuild -workspace MapApp.xcworkspace -scheme MapApp -sdk iphoneos -configuration Release