ENV['RCT_NEW_ARCH_ENABLED'] = '0'

use_frameworks! :linkage => :static
use_modular_headers!

require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '15.1'
prepare_react_native_project!

target 'MapApp' do
  # Google Maps ayarlarını etkinleştiriyoruz
  $RNMapsAppleMaps = false 
  $RNMapsGoogleMaps = true

  config = use_native_modules!

  use_react_native!(
    :path => "../node_modules/react-native",
    :hermes_enabled => true,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Google Maps köprüsü ve kütüphaneleri
  pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  post_install do |installer|
    react_native_post_install(installer, config[:reactNativePath])
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Genel Ayarlar
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        
        # --- dSYM HATASI İÇİN EKLENEN KISIM ---
        # Bu ayar hermes ve diğer podlar için dSYM üretilmesini sağlar
        config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
        # -------------------------------------

        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        
        # react-native-maps ve genel yeni mimariyi kapatma
        if target.name.include?('react-native-maps') || target.name == 'MapApp'
           config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_NEW_ARCH_ENABLED=0'
           config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_FABRIC_ENABLED=0'
        end

        if target.name.include?('gRPC')
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'GRPC_BAZEL_BUILD=1'
        end
      end
    end
  end
end