platform :ios, '15.4'
use_frameworks! :linkage => :static
$RN_FOLLY_VERSION = '2021.07.22.00'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
use_frameworks! :linkage => linkage.to_sym if linkage

target 'MapApp' do
  use_native_modules!

  flags = get_default_flags()

  use_react_native!(
    :path => "../node_modules/react-native",
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path

  # Boost: sadece patched podspec kullan
  pod 'boost', :podspec => './ios/boost-patched/boost.podspec'

  pod 'RCT-Folly', :podspec => '../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec'

  target 'MapAppTests' do
    inherit! :complete
  end
end

post_install do |installer|
  react_native_post_install(installer, "../node_modules/react-native", :mac_catalyst_enabled => false)

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.4'

      # C++ standard
      config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
      config.build_settings['CXX_STANDARD'] = '17'
      config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
    end
  end

  # Google Maps macro
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-maps'
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'HAVE_GOOGLE_MAPS=1']
      end
    end
  end
end
